name: Build FAP

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
  schedule:
    - cron: "1 1 * * *"

permissions:
  contents: write

jobs:
  ufbt-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: dev channel
            sdk-channel: dev
          - name: release channel
            sdk-channel: release
    name: 'ufbt: Build for ${{ matrix.name }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.sdk-channel }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

  publish-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: ufbt-build
    runs-on: ubuntu-latest
    steps:
      - name: Download app artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ github.event.repository.name }}-release-*
          path: release-artifacts
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/**/*.fap
          fail_on_unmatched_files: true
          generate_release_notes: true
          overwrite_files: true
